global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'eventsourcing'
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:7214']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']